/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author luci
 */
public class Pag2 extends javax.swing.JFrame {

    /**
     * Creates new form pag3
     */
    Pag1 pag1_elementos;
    // Cadastro de Professores
    private String id_professor;
    private String tipo_documento;
    private String numero_documento;
    private String nome;
    private String data_nascimento;
    private String sexo;
    private String nome_social;
    private String nacionalidade;
    private String bolsa_produtividade;
    private String email;
    private String instituicao_origem;
    private String nivel;
    private String ano_tit;
    private String pais_tit;
    private String instituicao_tit;
    private String tipo_vinculo;
    private String regime_trabalho;
    private String categoria;
    private String carga_horaria_sem;
    private String data_inicio_vinc;
    private String data_fim_vinc;
    private String ppp;
    private String ppi;
    private String pbtc;
    
    public Pag2(Pag1 pag1_elementos) {
        this.pag1_elementos = pag1_elementos;
        initComponents();
    }
    
    public Pag2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passaporte = new javax.swing.JRadioButton();
        rg = new javax.swing.JRadioButton();
        cpf = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        nome_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nome_social_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        nacionalidade_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sim = new javax.swing.JRadioButton();
        nao = new javax.swing.JRadioButton();
        instituicao_origem_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        graduacao = new javax.swing.JRadioButton();
        especializacao = new javax.swing.JRadioButton();
        mestrado = new javax.swing.JRadioButton();
        doutorado = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pais_tit_field = new javax.swing.JTextField();
        instituicao_tit_field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        servidor = new javax.swing.JRadioButton();
        clt = new javax.swing.JRadioButton();
        juridica = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        exclusiva = new javax.swing.JRadioButton();
        vinteH = new javax.swing.JRadioButton();
        quarentaH = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        permanente = new javax.swing.JRadioButton();
        colaborador = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        id_professor_field = new javax.swing.JFormattedTextField();
        numero_documento_field = new javax.swing.JFormattedTextField();
        data_nascimento_field = new javax.swing.JFormattedTextField();
        ano_tit_field = new javax.swing.JFormattedTextField();
        data_fim_vinc_field = new javax.swing.JFormattedTextField();
        data_inicio_vinc_field = new javax.swing.JFormattedTextField();
        carga_horaria_sem_field = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ppp_field = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ppi_field = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        pbtc_field = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/luci/Documentos/EngSoftware/trabalhoSubmissao/src/icons/settings.png")); // NOI18N
        jLabel1.setText("Cadastro de Professores");

        jLabel2.setText("ID Professor:");

        jLabel3.setText("Número do Documento:");

        jLabel4.setText(" Tipo de Documento:");

        buttonGroup1.add(passaporte);
        passaporte.setText("Passaporte");
        passaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passaporteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rg);
        rg.setText("RG");
        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        buttonGroup1.add(cpf);
        cpf.setText("CPF");
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome:");

        jLabel6.setText("Nome Social:");

        jLabel7.setText("Data de Nascimento:");

        jLabel8.setText("Sexo:");

        buttonGroup2.add(masculino);
        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });

        buttonGroup2.add(feminino);
        feminino.setText("Feminino");
        feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femininoActionPerformed(evt);
            }
        });

        jLabel9.setText("Nacionalidade:");

        jLabel10.setText("E-mail:");

        jLabel11.setText("Bolsa de Produtividade e Pesquisa?");

        buttonGroup3.add(sim);
        sim.setText("Sim");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });

        buttonGroup3.add(nao);
        nao.setText("Não");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });

        jLabel12.setText("Instituição de origem:");

        jLabel13.setText("Nível:");

        graduacao.setText("Graduação");
        graduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graduacaoActionPerformed(evt);
            }
        });

        especializacao.setText("Especialização");
        especializacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especializacaoActionPerformed(evt);
            }
        });

        mestrado.setText("Mestrado");
        mestrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mestradoActionPerformed(evt);
            }
        });

        doutorado.setText("Doutorado");
        doutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doutoradoActionPerformed(evt);
            }
        });

        jLabel14.setText("Ano da Titulação:");

        jLabel15.setText("País da Titulação:");

        jLabel16.setText("Instituição da Titulação:");

        jLabel17.setText("Tipo de Vínculo com a Instituição:");

        servidor.setText("Servidor Público");
        servidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servidorActionPerformed(evt);
            }
        });

        clt.setText("CLT");
        clt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cltActionPerformed(evt);
            }
        });

        juridica.setText("Pessoa Jurídica");
        juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juridicaActionPerformed(evt);
            }
        });

        jLabel18.setText("Regime de Trabalho:");

        exclusiva.setText("Dedicação Exclusiva");
        exclusiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exclusivaActionPerformed(evt);
            }
        });

        vinteH.setText("20H");
        vinteH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinteHActionPerformed(evt);
            }
        });

        quarentaH.setText("40H");
        quarentaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarentaHActionPerformed(evt);
            }
        });

        jLabel19.setText("Categoria:");

        permanente.setText("Permanente");
        permanente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permanenteActionPerformed(evt);
            }
        });

        colaborador.setText("Colaborador");
        colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaboradorActionPerformed(evt);
            }
        });

        jLabel20.setText(" Carga Horária Semanal:");

        jLabel21.setText("Data de início do vínculo com o programa:");

        jLabel22.setText("Data de fim do vínculo com o programa:");

        jLabel23.setText("Participação em Projetos de Pesquisa (IDs Projetos):");

        jLabel24.setText("Participação em Produções Intelectuais (IDs Produções):");

        jLabel25.setText("Participação em Bancas de Trabalho de Conclusão (IDs Bancas):");

        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/home/luci/Documentos/EngSoftware/trabalhoSubmissao/src/icons/left-arrow.png")); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon("/home/luci/Documentos/EngSoftware/trabalhoSubmissao/src/icons/right-arrow.png")); // NOI18N
        b2.setText("Próximo");
        b2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        id_professor_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        numero_documento_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        data_nascimento_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        ano_tit_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        data_fim_vinc_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        data_inicio_vinc_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        carga_horaria_sem_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        ppp_field.setColumns(20);
        ppp_field.setRows(5);
        jScrollPane1.setViewportView(ppp_field);

        ppi_field.setColumns(20);
        ppi_field.setRows(5);
        jScrollPane2.setViewportView(ppi_field);

        pbtc_field.setColumns(20);
        pbtc_field.setRows(5);
        jScrollPane3.setViewportView(pbtc_field);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(instituicao_tit_field)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(nacionalidade_field, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addGap(3, 3, 3)
                                            .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(id_professor_field, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabel3)
                                            .addGap(2, 2, 2)
                                            .addComponent(numero_documento_field, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(nome_field)
                                        .addComponent(nome_social_field)
                                        .addComponent(instituicao_origem_field))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pais_tit_field, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addGap(4, 4, 4)
                                                .addComponent(ano_tit_field, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel19))
                                            .addComponent(carga_horaria_sem_field, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(data_inicio_vinc_field, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(colaborador)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(permanente)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(6, 6, 6)
                                                    .addComponent(masculino))
                                                .addComponent(jLabel7)))
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(passaporte)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rg)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpf))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(data_nascimento_field, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addComponent(feminino)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(graduacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(especializacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mestrado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doutorado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(servidor))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nao)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(juridica))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exclusiva)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vinteH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b2)
                                            .addComponent(quarentaH)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel21)
                                .addGap(118, 118, 118)
                                .addComponent(jLabel22)
                                .addGap(3, 3, 3)
                                .addComponent(data_fim_vinc_field, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(68, 68, 68)
                                            .addComponent(jLabel23))
                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jButton1))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(passaporte)
                    .addComponent(rg)
                    .addComponent(cpf)
                    .addComponent(id_professor_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero_documento_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(data_nascimento_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nome_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nome_social_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(masculino)
                    .addComponent(feminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionalidade_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(sim)
                    .addComponent(nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(graduacao)
                        .addComponent(especializacao)
                        .addComponent(mestrado)
                        .addComponent(doutorado))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(instituicao_origem_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(instituicao_tit_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(servidor)
                    .addComponent(clt)
                    .addComponent(juridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(exclusiva)
                    .addComponent(vinteH)
                    .addComponent(quarentaH)
                    .addComponent(jLabel15)
                    .addComponent(pais_tit_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(colaborador)
                    .addComponent(permanente)
                    .addComponent(ano_tit_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(data_fim_vinc_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_inicio_vinc_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carga_horaria_sem_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(b2))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pag1 v1 = new Pag1();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    PDF pdf2;
    
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        
        pdf2 = new PDF();
        
        pdf2.setField("ID Professor: "+id_professor);
        pdf2.setField("Número do Documento: "+numero_documento);
        pdf2.setField("Tipo do Documento: "+tipo_documento);
        pdf2.setField("Nome: "+nome);
        pdf2.setField("Data de Nascimento: "+data_nascimento);
        pdf2.setField("Nome Social: "+nome_social);
        pdf2.setField("Sexo: "+sexo);
        pdf2.setField("Bolsa de Produtividade e Pesquisa? "+bolsa_produtividade);
        pdf2.setField("Nível: "+nivel);
        pdf2.setField("Tipo de Vínculo com a Instituição:: "+tipo_vinculo);
        pdf2.setField("Regime de Trabalho: "+regime_trabalho);
        pdf2.setField("Categoria: "+categoria);
        pdf2.setField("Nacionalidade: "+nacionalidade);
        pdf2.setField("E-mail: "+email);
        pdf2.setField("Instituição de origem: "+instituicao_origem);
        pdf2.setField("Ano da Titulação: "+ano_tit);
        pdf2.setField("País da Titulação: "+pais_tit);
        pdf2.setField("Instituição da Titulação: "+instituicao_tit);
        pdf2.setField("Carga Horária Semanal: "+carga_horaria_sem);
        pdf2.setField("Data de início do vínculo com o programa: "+data_inicio_vinc);
        pdf2.setField("Data de fim do vínculo com o programa: "+data_fim_vinc);
        pdf2.setField("Participação em Projetos de Pesquisa (IDs Projetos): "+ppp);
        pdf2.setField("Participação em Produções Intelectuais (IDs Produções): "+ppi);
        pdf2.setField("Participação em Bancas de Trabalho de Conclusão (IDs Bancas): "+pbtc);
        pdf2.setField("Tipo de Documento: "+tipo_documento);
        
        //Cadastro de Professores
        this.id_professor = id_professor_field.getText();
        this.numero_documento = numero_documento_field.getText();
        if(passaporte.isSelected()){
            this.tipo_documento = "Passaporte";
        }
        if(rg.isSelected()){
            this.tipo_documento = "RG";
        }
        if(cpf.isSelected()){
            this.tipo_documento = "CPF";
        }
        this.nome = nome_field.getText();
        this.data_nascimento = data_nascimento_field.getText();
        this.nome_social = nome_social_field.getText();
        if(masculino.isSelected()){
            this.sexo = "Masculino";
        }
        if(feminino.isSelected()){
            this.sexo = "Feminino";
        }
        if(sim.isSelected()){
            this.bolsa_produtividade = "Sim";
        }
        if(nao.isSelected()){
            this.bolsa_produtividade = "Não";
        }
        if(graduacao.isSelected()){
            this.nivel = "Graduação";
        }
        if(especializacao.isSelected()){
            this.nivel = "Especialização";
        }if(mestrado.isSelected()){
            this.nivel = "Mestrado";
        }
        if(doutorado.isSelected()){
            this.nivel = "Doutorado";
        }
        if(servidor.isSelected()){
            this.tipo_vinculo = "Servidor Público";
        }
        if(clt.isSelected()){
            this.tipo_vinculo = "CLT";
        }
        if(juridica.isSelected()){
            this.tipo_vinculo = "Pessoa jurídica";
        }
        if(exclusiva.isSelected()){
            this.regime_trabalho = "Dedicação exclusiva";
        }
        if(quarentaH.isSelected()){
            this.regime_trabalho = "40H";
        }
        if(vinteH.isSelected()){
            this.regime_trabalho = "20H";
        }
        if(colaborador.isSelected()){
            this.categoria = "Colaborador(a)";
        }
        if(permanente.isSelected()){
            this.categoria = "Permanente";
        }
        this.nacionalidade = nacionalidade_field.getText();
        this.email = email_field.getText();
        this.instituicao_origem = instituicao_origem_field.getText();
        this.ano_tit = ano_tit_field.getText();
        this.pais_tit = pais_tit_field.getText();
        this.instituicao_tit = instituicao_tit_field.getText();
        this.carga_horaria_sem = carga_horaria_sem_field.getText();
        this.data_inicio_vinc = data_inicio_vinc_field.getText();
        this.data_fim_vinc = data_fim_vinc_field.getText();
        this.ppp = ppp_field.getText();
        this.ppi = ppi_field.getText();
        this.pbtc = pbtc_field.getText();
        
        Pag3 p3 = new Pag3(this.pag1_elementos, this);
        p3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b2ActionPerformed

    private void passaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passaporteActionPerformed
        
    }//GEN-LAST:event_passaporteActionPerformed

    private void vinteHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinteHActionPerformed
        
    }//GEN-LAST:event_vinteHActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        
    }//GEN-LAST:event_rgActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        
    }//GEN-LAST:event_cpfActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
        
    }//GEN-LAST:event_masculinoActionPerformed

    private void femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femininoActionPerformed
        
    }//GEN-LAST:event_femininoActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        
    }//GEN-LAST:event_simActionPerformed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        
    }//GEN-LAST:event_naoActionPerformed

    private void graduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graduacaoActionPerformed
        
    }//GEN-LAST:event_graduacaoActionPerformed

    private void especializacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especializacaoActionPerformed
        
    }//GEN-LAST:event_especializacaoActionPerformed

    private void mestradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mestradoActionPerformed
        
    }//GEN-LAST:event_mestradoActionPerformed

    private void doutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doutoradoActionPerformed
        
    }//GEN-LAST:event_doutoradoActionPerformed

    private void servidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servidorActionPerformed
        
    }//GEN-LAST:event_servidorActionPerformed

    private void cltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cltActionPerformed
        
    }//GEN-LAST:event_cltActionPerformed

    private void juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juridicaActionPerformed
        
    }//GEN-LAST:event_juridicaActionPerformed

    private void exclusivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exclusivaActionPerformed
        
    }//GEN-LAST:event_exclusivaActionPerformed

    private void quarentaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarentaHActionPerformed
        
    }//GEN-LAST:event_quarentaHActionPerformed

    private void colaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaboradorActionPerformed
        
    }//GEN-LAST:event_colaboradorActionPerformed

    private void permanenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permanenteActionPerformed
        
    }//GEN-LAST:event_permanenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pag2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pag2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ano_tit_field;
    private javax.swing.JButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JFormattedTextField carga_horaria_sem_field;
    private javax.swing.JRadioButton clt;
    private javax.swing.JRadioButton colaborador;
    private javax.swing.JRadioButton cpf;
    private javax.swing.JFormattedTextField data_fim_vinc_field;
    private javax.swing.JFormattedTextField data_inicio_vinc_field;
    private javax.swing.JFormattedTextField data_nascimento_field;
    private javax.swing.JRadioButton doutorado;
    private javax.swing.JTextField email_field;
    private javax.swing.JRadioButton especializacao;
    private javax.swing.JRadioButton exclusiva;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JRadioButton graduacao;
    private javax.swing.JFormattedTextField id_professor_field;
    private javax.swing.JTextField instituicao_origem_field;
    private javax.swing.JTextField instituicao_tit_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton juridica;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JRadioButton mestrado;
    private javax.swing.JTextField nacionalidade_field;
    private javax.swing.JRadioButton nao;
    private javax.swing.JTextField nome_field;
    private javax.swing.JTextField nome_social_field;
    private javax.swing.JFormattedTextField numero_documento_field;
    private javax.swing.JTextField pais_tit_field;
    private javax.swing.JRadioButton passaporte;
    private javax.swing.JTextArea pbtc_field;
    private javax.swing.JRadioButton permanente;
    private javax.swing.JTextArea ppi_field;
    private javax.swing.JTextArea ppp_field;
    private javax.swing.JRadioButton quarentaH;
    private javax.swing.JRadioButton rg;
    private javax.swing.JRadioButton servidor;
    private javax.swing.JRadioButton sim;
    private javax.swing.JRadioButton vinteH;
    // End of variables declaration//GEN-END:variables
}
